### ISSUE TITLE
fontie.pixelsvsbytes.com is down

### ISSUE THREAD

**Issue by ForestJohnson** [letorbi/fontie#4]
I am sad to see this tool go! It was really awesome. Any chance you could open-source the HTML form part of the app as well? I would be happy to see if I can deploy it myself  on my own server.

**Comment by letorbi** [comment]
Hi Forest,

sorry for the late answer - I was quite busy during August and had not much time for my own projects. I've just checked and Fontie seems to be working again. Can you confirm this?

Regards,
Torben

**Comment by letorbi** [comment]
Regarding the release of the frontend code: I'm actually planning to release Fontie as a whole package for more than a year now. Unfortunately this still requires some extra work and I'm short on time for private projects right now...

**Comment by ForestJohnson** [comment]
That's fine, thanks for the work you do :heart:
